import PDFDocument from 'pdfkit';

type InvoiceLine = {
  name?: string;
  quantity?: number;
  qty?: number;
  unit?: string;
  productCategory?: string | null;
  grade?: string;
  rslDaysAtDelivery?: number;
};

export type InvoicePdfInput = {
  invoiceNumber: string;
  issuedAt: Date;
  orderCode: string;
  amountPaise: number;
  supplierLabel: string;
  consumerLabel: string;
  deliveryAddress?: string | null;
  lines: InvoiceLine[];
  isDraft?: boolean;
};

function money(paise: number) {
  return `INR ${(paise / 100).toFixed(2)}`;
}

export function buildInvoicePdf(input: InvoicePdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c) => chunks.push(c as Buffer));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc
      .fontSize(20)
      .fillColor('#835400')
      .text('BUDDIES', { continued: false });
    doc
      .fontSize(11)
      .fillColor('#514535')
      .text('Tax Invoice / Delivery Invoice');
    doc.moveDown(0.5);
    doc
      .fontSize(10)
      .fillColor('#211B13')
      .text(`Invoice: ${input.invoiceNumber}`)
      .text(`Order: ${input.orderCode}`)
      .text(`Issued: ${input.issuedAt.toISOString().slice(0, 10)}`);

    doc.moveDown();
    doc.fontSize(11).fillColor('#835400').text('Parties');
    doc
      .fontSize(10)
      .fillColor('#211B13')
      .text(`Supplier: ${input.supplierLabel}`)
      .text(`Buyer: ${input.consumerLabel}`);
    if (input.deliveryAddress) {
      doc.text(`Delivery: ${input.deliveryAddress}`);
    }

    doc.moveDown();
    doc.fontSize(11).fillColor('#835400').text('Line items');
    doc.moveDown(0.3);

    const startY = doc.y;
    doc
      .fontSize(9)
      .fillColor('#514535')
      .text('Item', 48, startY, { width: 220 })
      .text('Qty', 270, startY, { width: 60 })
      .text('Unit', 340, startY, { width: 60 })
      .text('Notes', 410, startY, { width: 140 });
    doc
      .moveTo(48, startY + 14)
      .lineTo(547, startY + 14)
      .strokeColor('#D6C3AF')
      .stroke();

    let y = startY + 22;
    const lines = input.lines.length
      ? input.lines
      : [{ name: 'Winning bid supply', quantity: 1, unit: 'lot' }];

    for (const line of lines) {
      const name = line.name ?? 'Item';
      const qty = String(line.quantity ?? line.qty ?? '');
      const unit = line.unit ?? '';
      const notes = [
        line.grade ? `Grade ${line.grade}` : null,
        line.rslDaysAtDelivery != null ? `RSL ${line.rslDaysAtDelivery}d` : null,
        line.productCategory ?? null,
      ]
        .filter(Boolean)
        .join(' · ');

      doc
        .fontSize(10)
        .fillColor('#211B13')
        .text(name, 48, y, { width: 220 })
        .text(qty, 270, y, { width: 60 })
        .text(unit, 340, y, { width: 60 })
        .text(notes, 410, y, { width: 140 });
      y = doc.y + 8;
      if (y > 720) {
        doc.addPage();
        y = 48;
      }
    }

    doc.y = Math.max(doc.y, y) + 12;
    doc
      .moveTo(48, doc.y)
      .lineTo(547, doc.y)
      .strokeColor('#D6C3AF')
      .stroke();
    doc.moveDown();
    doc
      .fontSize(14)
      .fillColor('#835400')
      .text(`Total payable: ${money(input.amountPaise)}`, { align: 'right' });

    doc.moveDown(1.5);
    doc
      .fontSize(9)
      .fillColor('#847563')
      .text(
        'Generated by Buddies after digital challan sign-off. This document is for offline settlement records.',
        { align: 'left' },
      );

    doc.end();
  });
}
